/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Admin
 */
public class calculatorr extends javax.swing.JFrame {

    /**
     * Creates new form calculatorr
     */
    double numb,answer;
    int calculation;
    
    public calculatorr() {
        initComponents();
        RbtnOn.setEnabled(false);
    }
    public void arithmeticoperation() 
    {
    switch (calculation){
        case 1:
            answer = numb + Double.parseDouble(txtshow.getText());
            txtshow.setText(Double.toString(answer));
            break;
            
             case 2:
            answer = numb - Double.parseDouble(txtshow.getText());
            txtshow.setText(Double.toString(answer));
            break;
            
             case 3:
            answer = numb * Double.parseDouble(txtshow.getText());
            txtshow.setText(Double.toString(answer));
            break;
            
             case 4:
            answer = numb / Double.parseDouble(txtshow.getText());
            txtshow.setText(Double.toString(answer));
            break;
            
    }
    }
    public void enable()
    {
    txtshow.setEnabled(true);
    
     RbtnOn.setEnabled(false);
    RbtnOff.setEnabled(true);
    
    Btn0.setEnabled(true);
    Btn1.setEnabled(true);
    Btn2.setEnabled(true);
    Btn3.setEnabled(true);
    Btn4.setEnabled(true);
    Btn5.setEnabled(true);
    Btn6.setEnabled(true);
    Btn7.setEnabled(true);
    Btn8.setEnabled(true);
    Btn9.setEnabled(true);
    Btnadd.setEnabled(true);
    Btnsub.setEnabled(true);
    Btnmul.setEnabled(true);
    Btndiv.setEnabled(true);
    BtnClear.setEnabled(true);
    Btnpoint.setEnabled(true);
    Btnequal.setEnabled(true);
    BtnBack.setEnabled(true);
    }
    
    public void disable()
    {
    txtshow.setEnabled(false);
    
    RbtnOn.setEnabled(true);
    RbtnOff.setEnabled(false);
    
    Btn0.setEnabled(false);
    Btn1.setEnabled(false);
    Btn2.setEnabled(false);
    Btn3.setEnabled(false);
    Btn4.setEnabled(false);
    Btn5.setEnabled(false);
    Btn6.setEnabled(false);
    Btn7.setEnabled(false);
    Btn8.setEnabled(false);
    Btn9.setEnabled(false);
    Btnadd.setEnabled(false);
    Btnsub.setEnabled(false);
    Btnmul.setEnabled(false);
    Btndiv.setEnabled(false);
    BtnClear.setEnabled(false);
    Btnpoint.setEnabled(false);
    Btnequal.setEnabled(false);
    BtnBack.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtshow = new javax.swing.JTextField();
        RbtnOn = new javax.swing.JRadioButton();
        RbtnOff = new javax.swing.JRadioButton();
        BtnBack = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        Btnmul = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btnequal = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        Btnpoint = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btndiv = new javax.swing.JButton();
        Btnsub = new javax.swing.JButton();
        Btnadd = new javax.swing.JButton();
        Lblshow = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setType(java.awt.Window.Type.UTILITY);

        txtshow.setEditable(false);
        txtshow.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        txtshow.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(RbtnOn);
        RbtnOn.setText("ON");
        RbtnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnOnActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtnOff);
        RbtnOff.setText("OFF");
        RbtnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnOffActionPerformed(evt);
            }
        });

        BtnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnBack.setText("<--");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnClear.setText("C");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        Btnmul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnmul.setText("x");
        Btnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmulActionPerformed(evt);
            }
        });

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btnequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnequal.setText("=");
        Btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnequalActionPerformed(evt);
            }
        });

        Btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        Btnpoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnpoint.setText(".");
        Btnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpointActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btndiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btndiv.setText("/");
        Btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndivActionPerformed(evt);
            }
        });

        Btnsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnsub.setText("-");
        Btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsubActionPerformed(evt);
            }
        });

        Btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnadd.setText("+");
        Btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaddActionPerformed(evt);
            }
        });

        Lblshow.setForeground(new java.awt.Color(255, 51, 255));
        Lblshow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtshow)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RbtnOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RbtnOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addComponent(Lblshow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lblshow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtshow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbtnOff)
                    .addComponent(RbtnOn)
                    .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnClear))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn7)
                    .addComponent(Btn8)
                    .addComponent(Btn9)
                    .addComponent(Btnmul))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn4)
                    .addComponent(Btn5)
                    .addComponent(Btn6)
                    .addComponent(Btndiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn1)
                    .addComponent(Btn2)
                    .addComponent(Btn3)
                    .addComponent(Btnsub))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn0)
                    .addComponent(Btnpoint)
                    .addComponent(Btnequal)
                    .addComponent(Btnadd))
                .addContainerGap())
        );

        RbtnOn.getAccessibleContext().setAccessibleName("RbtnOn");
        RbtnOff.getAccessibleContext().setAccessibleName("RbtnOff");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
       
        int length = txtshow.getText().length();
        int number = txtshow.getText().length() - 1;
        String store;
        
        if (length > 0)
        {
            StringBuilder back = new StringBuilder(txtshow.getText());
            back.deleteCharAt(number);
            store=back.toString();
            txtshow.setText(store);
            
            
        }
            
        
    }//GEN-LAST:event_BtnBackActionPerformed

    private void RbtnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnOffActionPerformed
        disable();
    }//GEN-LAST:event_RbtnOffActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        txtshow.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        txtshow.setText(txtshow.getText()+"7");
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        txtshow.setText(txtshow.getText()+"8");
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        txtshow.setText(txtshow.getText()+"9");
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
       txtshow.setText(txtshow.getText()+"4");
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
       txtshow.setText(txtshow.getText()+"5");
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        txtshow.setText(txtshow.getText()+"6");
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        txtshow.setText(txtshow.getText()+"1");
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        txtshow.setText(txtshow.getText()+"2");
    }//GEN-LAST:event_Btn2ActionPerformed

    private void BtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnequalActionPerformed
       arithmeticoperation();
       Lblshow.setText("");
    }//GEN-LAST:event_BtnequalActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        txtshow.setText(txtshow.getText()+"0");
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpointActionPerformed
        txtshow.setText(txtshow.getText()+".");
    }//GEN-LAST:event_BtnpointActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        txtshow.setText(txtshow.getText()+"3");
    }//GEN-LAST:event_Btn3ActionPerformed

    private void BtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmulActionPerformed
        numb = Double.parseDouble(txtshow.getText());
       calculation = 3;
       txtshow.setText("");
       Lblshow.setText(numb +"x");
    }//GEN-LAST:event_BtnmulActionPerformed

    private void BtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndivActionPerformed
        numb = Double.parseDouble(txtshow.getText());
       calculation = 4;
       txtshow.setText("");
       Lblshow.setText(numb +"/");
    }//GEN-LAST:event_BtndivActionPerformed

    private void BtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsubActionPerformed
 numb = Double.parseDouble(txtshow.getText());
       calculation = 2;
       txtshow.setText("");
       Lblshow.setText(numb +"-");        
    }//GEN-LAST:event_BtnsubActionPerformed

    private void BtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaddActionPerformed
       numb = Double.parseDouble(txtshow.getText());
       calculation = 1;
       txtshow.setText("");
       Lblshow.setText(numb +"+");
       
       
    }//GEN-LAST:event_BtnaddActionPerformed

    private void RbtnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnOnActionPerformed
       enable();
    }//GEN-LAST:event_RbtnOnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton Btnadd;
    private javax.swing.JButton Btndiv;
    private javax.swing.JButton Btnequal;
    private javax.swing.JButton Btnmul;
    private javax.swing.JButton Btnpoint;
    private javax.swing.JButton Btnsub;
    private javax.swing.JLabel Lblshow;
    private javax.swing.JRadioButton RbtnOff;
    private javax.swing.JRadioButton RbtnOn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTextField txtshow;
    // End of variables declaration//GEN-END:variables
}
